# Generated by Django 5.1.2 on 2024-10-26 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rename_aage_profile_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='first_mame',
            new_name='first_name',
        ),
    ]
